# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unique_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('XML', 'XML'), ('PDF', 'PDF')], max_length=100)),
                ('xml_file', models.FileField(upload_to='xml_files')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdf_files')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
            },
        ),
    ]
