# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 09:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project_folder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geschaft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('variables', django.contrib.postgres.fields.jsonb.JSONField(default='{}')),
                ('project_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_folder.ProjectFolder')),
            ],
            options={
                'verbose_name': 'Geschäft',
                'verbose_name_plural': 'Geschäfte',
            },
        ),
    ]
