# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geschaft', '0001_initial'),
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geschaft',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='template.Template'),
        ),
    ]
