# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kanzlei', '0002_kanzlei_container'),
        ('auth', '0008_alter_user_username_max_length'),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConventecUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('position', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(choices=[('admin', 'Kanzlei Admin'), ('manager', 'Projektmanager'), ('mitarbeiter', 'Projektmitarbeiter')], max_length=100)),
                ('kanzlei', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanzlei.Kanzlei')),
                ('teams', models.ManyToManyField(blank=True, to='team.Team')),
            ],
        ),
    ]
