# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-08 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('document', '0001_initial'),
        ('kanzlei', '0001_initial'),
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=3000)),
                ('type', models.CharField(choices=[('container', 'Enthält nur Container'), ('geschafte', 'Enthält nur Geschäfte')], max_length=100)),
                ('kanzleien', models.ManyToManyField(blank=True, null=True, related_name='kanzlei_templates', to='kanzlei.Kanzlei')),
                ('parent_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='template.Container')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=3000)),
                ('documents', models.ManyToManyField(blank=True, to='document.Document')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='form.Form')),
                ('kanzleien', models.ManyToManyField(blank=True, to='kanzlei.Kanzlei')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.AddField(
            model_name='container',
            name='template',
            field=models.ManyToManyField(blank=True, null=True, to='template.Template'),
        ),
    ]
