# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 08:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('template', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='container',
            old_name='template',
            new_name='templates',
        ),
    ]
